# Generated by Django 4.2.28 on 2026-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Fenykep neve')),
                ('image', models.ImageField(upload_to='photos/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
