name: Deploy to OKD via Terraform

on:
  push:
    branches:
      - main
      - master

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup Kubeconfig
        run: |
          kubectl config set-cluster okd --server=${{ secrets.OPENSHIFT_SERVER }} --insecure-skip-tls-verify=true --kubeconfig=/tmp/kubeconfig
          kubectl config set-credentials github-action --token=${{ secrets.OPENSHIFT_TOKEN }} --kubeconfig=/tmp/kubeconfig
          kubectl config set-context okd-context --cluster=okd --user=github-action --namespace=jonatanpribek-dev --kubeconfig=/tmp/kubeconfig
          kubectl config use-context okd-context --kubeconfig=/tmp/kubeconfig

      - name: Terraform Init
        working-directory: ./project/infrastructure
        env:
          KUBE_CONFIG_PATH: /tmp/kubeconfig
        run: |
          terraform init || true
          terraform force-unlock -force 0bd52ae0-1622-02c1-8632-816cdd60ecef

      - name: Terraform Apply
        working-directory: ./project/infrastructure
        env:
          KUBE_CONFIG_PATH: /tmp/kubeconfig
          TF_VAR_openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          TF_VAR_openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_namespace: "jonatanpribek-dev"
        run: terraform apply -auto-approve